### ISSUE TITLE
Issue with parsing data using eet_readsubject

### ISSUE THREAD

**Issue by VeeRuus** [smathot/eeg_eyetracking_parser#11]
The line of code that was executed: raw, events, metadata = eet.read_subject(36)

The parsing starts without issues and after converting the EDF file to ASC it quickly crashes. Below is the full traceback of the error (+ the last few lines in the console before):

Converted successfully: 296982 events, 5694020 samples, 900 blocks.

......./home/veeraruuskanen/.local/lib/python3.10/site-packages/eyelinkparser/_eyelinkparser.py:326: UserWarning: Trial ended while phase "trial" was still ongoing
  warnings.warn(
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 raw, events, metadata = eet.read_subject(36)

File ~/.local/lib/python3.10/site-packages/datamatrix/_functional/_memoize.py:236, in memoize._call_without_arguments(self, *args, **kwargs)
    229 if self._debug:
    230     print(
    231         '%s: executing for memkey %s'
    232         % (self.__name__, memkey)
    233     )
    234 return self._write_cache(
    235     memkey,
--> 236     self._fnc(*args, **kwargs)
    237 )

File ~/.local/lib/python3.10/site-packages/eeg_eyetracking_parser/_parsing.py:130, in read_subject(subject_nr, folder, trigger_parser, eeg_margin, min_sacc_dur, min_sacc_size, min_blink_dur, blink_annotation, saccade_annotation, eeg_preprocessing, save_preprocessing_output, plot_preprocessing, eye_kwargs, downsample_data_kwargs, drop_unused_channels_kwargs, rereference_channels_kwargs, create_eog_channels_kwargs, set_montage_kwargs, annotate_emg_kwargs, band_pass_filter_kwargs, autodetect_bad_channels_kwargs, run_ica_kwargs, auto_select_ica_kwargs, interpolate_bads_kwargs)
    128 dm = _read_eye_data(eye_path, metadata, eye_kwargs)
    129 if dm is not None and raw is not None:
--> 130     dm = _merge_eye_and_eeg_data(eye_path, raw, events, dm, min_sacc_dur,
    131                                  min_sacc_size, min_blink_dur,
    132                                  blink_annotation, saccade_annotation,
    133                                  eye_kwargs)
    134 if metadata is None and dm is not None:
    135     metadata = _dm_to_metadata(dm)

File ~/.local/lib/python3.10/site-packages/eeg_eyetracking_parser/_parsing.py:252, in _merge_eye_and_eeg_data(eye_path, raw, events, dm, min_sacc_dur, min_sacc_size, min_blink_dur, blink_annotation, saccade_annotation, eye_kwargs)
    249     logger.info('no traceprocessor specified, using default')
    250     eye_kwargs['traceprocessor'] = defaulttraceprocessor(
    251         blinkreconstruct=True, mode='advanced')
--> 252 bigdm = parse(folder=eye_path, trialphase='trial', phasefilter=only_trial,
    253               **eye_kwargs)
    254 # Valid rows are those rows in which there is an epoch 1. Since the epochs
    255 # are only parsed in dm (not in bigdm), we use indices in dm to filter both
    256 # dm and bigdm. The result is that dm and bigdm only contain rows that
    257 # should correspond to trials in the EEG recording.
    258 if '' in dm.t_onset_1:

File ~/.local/lib/python3.10/site-packages/eyelinkparser/__init__.py:30, in parse(parser, **kwdict)
     28 def parse(parser=EyeLinkParser, **kwdict):
---> 30     return parser(**kwdict).dm

File ~/.local/lib/python3.10/site-packages/eyelinkparser/_eyelinkparser.py:181, in EyeLinkParser.__init__(self, folder, ext, downsample, maxtracelen, traceprocessor, phasefilter, phasemap, trialphase, edf2asc_binary, multiprocess, asc_encoding, pupil_size, gaze_pos, time_trace)
    179 else:
    180     for fname in input_files:
--> 181         self.dm <<= self.parse_file(fname)
    182 operations.auto_type(self.dm)

File ~/.local/lib/python3.10/site-packages/eyelinkparser/_eyelinkparser.py:269, in EyeLinkParser.parse_file(self, path)
    266 # Use the much faster stack() routine if it's available. Requires
    267 # DataMatrix >= 1.0
    268 if hasattr(operations, 'stack'):
--> 269     self.filedm = operations.stack(trialdms)
    270 else:
    271     logging.warning(
    272         'updating to DataMatrix >= 1.0 will be much faster')

File ~/.local/lib/python3.10/site-packages/datamatrix/operations.py:127, in stack(*dms)
    123 # If the column already exists and is a series, modify the
    124 # depth to the longest column
    125 if isinstance(col, _MultiDimensionalColumn) and \
    126         len(col.shape) == 2:
--> 127     dm[name].depth = max(col.depth, dm[name].depth)
    128     stackdm[name].depth = max(col.depth, dm[name].depth)
    129 # The length doesn't need to be the same, but other than that
    130 # the shape of the columns needs to match

File ~/.local/lib/python3.10/site-packages/datamatrix/_datamatrix/_multidimensionalcolumn.py:316, in _MultiDimensionalColumn.__setattr__(self, key, val)
    311 """Catches assignments to the _seq attribute, which may need to be
    312 converted to memmap or a regular array depending on the loaded status.
    313 """
    314 if key != '_seq' or (isinstance(val, np.memmap) and not self.loaded) \
    315         or (not isinstance(val, np.memmap) and self.loaded):
--> 316     super().__setattr__(key, val)
    317     return
    318 # Convert to memory-mapped array

File ~/.local/lib/python3.10/site-packages/datamatrix/_datamatrix/_multidimensionalcolumn.py:182, in _MultiDimensionalColumn.depth(self, depth)
    180     seq[:] = np.nan
    181 seq[:, :self.depth] = self._seq
--> 182 self._seq = seq
    183 self._shape = (depth, )
    184 return

File ~/.local/lib/python3.10/site-packages/datamatrix/_datamatrix/_multidimensionalcolumn.py:320, in _MultiDimensionalColumn.__setattr__(self, key, val)
    318 # Convert to memory-mapped array
    319 self._init_seq()
--> 320 self._seq[:] = val

ValueError: could not broadcast input array from shape (900,135616) into shape (900,51627)

**Comment by smathot** [comment]
Fixed in DataMatrix https://github.com/open-cogsci/datamatrix/commit/e7c832abd3f91ad0eb74e304333dd75378147bd3.
